#!/usr/bin/env python3

import argparse

from metadata import get_full_metadata
from docker_utils import push_image


def main():

    try:

        parser = argparse.ArgumentParser(
            description="Push Docker image to registry"
        )

        parser.add_argument(
            "--app-repo",
            default=None,
            help="Application repository path",
        )

        parser.add_argument(
            "--version",
            required=True,
            help="Image version generated by the CI pipeline",
        )

        args = parser.parse_args()

        metadata = get_full_metadata(args.app_repo)

        metadata["version"] = args.version

        print("\n========== Docker Push ==========\n")

        print(f"Image      : {metadata['image_name']}")
        print(f"Version    : {args.version}")
        print(f"Branch     : {metadata['branch']}")
        print(f"Commit     : {metadata['commit']}")
        print(f"Author     : {metadata['author']}")
        print(f"Timestamp  : {metadata['timestamp']}")

        print("\n=================================\n")

        push_image(
            metadata=metadata,
            version=args.version,
        )

        print("\nImage pushed successfully.")

    except Exception as e:

        print(f"\nERROR: {e}")

        raise


if __name__ == "__main__":
    main()