#!/usr/bin/env python3

"""
Update images.json after a successful image build.
"""

import argparse
import json
from datetime import datetime
from pathlib import Path

from metadata import get_git_metadata


def update_images(images_file, application, version, build_number):
    """
    Update images.json with the latest build metadata.
    """

    images_file = Path(images_file)

    with images_file.open("r", encoding="utf-8") as f:
        data = json.load(f)

    git = get_git_metadata()

    app = data["applications"][application]

    app["image"] = application
    app["version"] = version
    app["commit"] = git["commit"]
    app["build"] = str(build_number)
    app["timestamp"] = datetime.utcnow().isoformat(timespec="seconds") + "Z"
    app["status"] = "SUCCESS"

    with images_file.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)


    print("\n========== Build Metadata ==========\n")

    print(json.dumps(app, indent=4))

    print("\nimages.json updated successfully.\n")


def main():

    parser = argparse.ArgumentParser(
        description="Update images.json after a successful build"
    )

    parser.add_argument(
        "--images",
        required=True,
        help="Path to images.json",
    )

    parser.add_argument(
        "--application",
        required=True,
        help="Application name",
    )

    parser.add_argument(
        "--version",
        required=True,
        help="Image version generated by the CI pipeline",
    )

    parser.add_argument(
        "--build-number",
        default="local",
        help="Jenkins build number",
    )

    args = parser.parse_args()

    update_images(
        images_file=args.images,
        application=args.application,
        version=args.version,
        build_number=args.build_number,
    )


if __name__ == "__main__":
    main()